language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t mailsky2010/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true mailsky2010/react-test-app npm run test

after_success: 
  - docker build -t docker-frontend:latest mailsky2010/docker-frontend:1.0 ./frontend
  - docker build -t docker-backend:latest mailsky2010/docker-backend:1.0  ./backend
  - docker build -t docker-nginx:latest mailsky2010/docker-nginx:1.0    ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push mailsky2010/docker-frontend:1.0
  - docker push mailsky2010/docker-backend:1.0 
  - docker push mailsky2010/docker-nginx:1.0 